/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingsystem_nerosa;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author FernanCarl
 */
public class MainDashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboardFrame.class.getName());
    private final CustomerDAO customerDAO = new CustomerDAO();
    private final AccountDAO accountDAO = new AccountDAO();
    private final TransactionDAO transactionDAO = new TransactionDAO();
    /**
     * Creates new form MainDashboardFrame
     */
    public MainDashboardFrame() {
        initComponents();
    }
    
    private int readInt(JTextField field, String label) {
        try {
            return Integer.parseInt(requiredText(field, label));
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException(label + " must be a valid number.");
        }
    }
    
    private String requiredText(JTextField field, String label) {
        String value = field.getText().trim();
        if (value.isEmpty()) {
            throw new IllegalArgumentException(label + " is required.");
        }
        return value;
    }
    
    private void clearCustomerFields() {
        firstNameField.setText("");
        lastNameField.setText("");
        emailField.setText("");
        phoneField.setText("");
    }

    private void clearAccountFields() {
        accountTypeField.setText("");
        initialBalanceField.setText("");
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private BigDecimal readAmount(JTextField field, String label) {
        try {
            BigDecimal amount = new BigDecimal(requiredText(field, label));

            if (amount.compareTo(BigDecimal.ZERO) < 0) {
                throw new IllegalArgumentException(label + " cannot be negative.");
            }

            return amount;
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException(label + " must be a valid amount.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlHeader = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        navPanel = new javax.swing.JPanel();
        customersButton = new javax.swing.JButton();
        accountsButton = new javax.swing.JButton();
        transactionButton = new javax.swing.JButton();
        logsButton = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        pnlCustomerCard = new javax.swing.JPanel();
        customerDetailsTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        pnlAccountCard = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        customerIdField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        accountTypeField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        initialBalanceField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        addAccountButton = new javax.swing.JButton();
        addAccountButton1 = new javax.swing.JButton();
        outputPanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banking System - Main Dashboard");
        setBackground(new java.awt.Color(248, 250, 252));

        pnlHeader.setBackground(new java.awt.Color(28, 45, 74));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 22, 18, 22));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        textPanel.setOpaque(false);
        textPanel.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Simple Banking System");
        textPanel.add(lblTitle, java.awt.BorderLayout.NORTH);

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(208, 218, 232));
        lblSubtitle.setText("Create customers, open accounts, and navigate banking records.");
        textPanel.add(lblSubtitle, java.awt.BorderLayout.SOUTH);

        pnlHeader.add(textPanel, java.awt.BorderLayout.WEST);

        navPanel.setOpaque(false);
        navPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 0));

        customersButton.setBackground(new java.awt.Color(51, 102, 204));
        customersButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customersButton.setForeground(new java.awt.Color(255, 255, 255));
        customersButton.setText("Customers");
        customersButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        customersButton.setBorderPainted(false);
        customersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customersButton.setFocusPainted(false);
        customersButton.setOpaque(true);
        customersButton.addActionListener(this::customersButtonActionPerformed);
        navPanel.add(customersButton);

        accountsButton.setBackground(new java.awt.Color(51, 102, 204));
        accountsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        accountsButton.setForeground(new java.awt.Color(255, 255, 255));
        accountsButton.setText("Accounts");
        accountsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        accountsButton.setBorderPainted(false);
        accountsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountsButton.setFocusPainted(false);
        accountsButton.setOpaque(true);
        accountsButton.addActionListener(this::accountsButtonActionPerformed);
        navPanel.add(accountsButton);

        transactionButton.setBackground(new java.awt.Color(51, 102, 204));
        transactionButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        transactionButton.setForeground(new java.awt.Color(255, 255, 255));
        transactionButton.setText("Transaction");
        transactionButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        transactionButton.setBorderPainted(false);
        transactionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transactionButton.setFocusPainted(false);
        transactionButton.setOpaque(true);
        transactionButton.addActionListener(this::transactionButtonActionPerformed);
        navPanel.add(transactionButton);

        logsButton.setBackground(new java.awt.Color(51, 102, 204));
        logsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logsButton.setForeground(new java.awt.Color(255, 255, 255));
        logsButton.setText("Transaction Logs");
        logsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        logsButton.setBorderPainted(false);
        logsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logsButton.setFocusPainted(false);
        logsButton.setOpaque(true);
        logsButton.addActionListener(this::logsButtonActionPerformed);
        navPanel.add(logsButton);

        pnlHeader.add(navPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.NORTH);

        body.setBackground(new java.awt.Color(248, 250, 252));
        body.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 22, 12, 22));
        body.setLayout(new java.awt.GridLayout(1, 2, 16, 0));

        pnlCustomerCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlCustomerCard.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240)), javax.swing.BorderFactory.createEmptyBorder(18, 18, 18, 18)));
        pnlCustomerCard.setLayout(new java.awt.GridBagLayout());

        customerDetailsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerDetailsTitle.setForeground(new java.awt.Color(30, 41, 59));
        customerDetailsTitle.setText("Customer Details");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlCustomerCard.add(customerDetailsTitle, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 85, 105));
        jLabel2.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlCustomerCard.add(jLabel2, gridBagConstraints);

        firstNameField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        firstNameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)), javax.swing.BorderFactory.createEmptyBorder(7, 9, 7, 9)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlCustomerCard.add(firstNameField, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 85, 105));
        jLabel3.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlCustomerCard.add(jLabel3, gridBagConstraints);

        lastNameField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lastNameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)), javax.swing.BorderFactory.createEmptyBorder(7, 9, 7, 9)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlCustomerCard.add(lastNameField, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(71, 85, 105));
        jLabel4.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlCustomerCard.add(jLabel4, gridBagConstraints);

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        emailField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)), javax.swing.BorderFactory.createEmptyBorder(7, 9, 7, 9)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlCustomerCard.add(emailField, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(71, 85, 105));
        jLabel5.setText("Phone Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlCustomerCard.add(jLabel5, gridBagConstraints);

        phoneField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        phoneField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)), javax.swing.BorderFactory.createEmptyBorder(7, 9, 7, 9)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlCustomerCard.add(phoneField, gridBagConstraints);

        addCustomerButton.setBackground(new java.awt.Color(51, 102, 204));
        addCustomerButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerButton.setText("Add Customer");
        addCustomerButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        addCustomerButton.setBorderPainted(false);
        addCustomerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCustomerButton.setFocusPainted(false);
        addCustomerButton.setOpaque(true);
        addCustomerButton.addActionListener(this::addCustomerButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlCustomerCard.add(addCustomerButton, gridBagConstraints);

        body.add(pnlCustomerCard);

        pnlAccountCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlAccountCard.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240)), javax.swing.BorderFactory.createEmptyBorder(18, 18, 18, 18)));
        pnlAccountCard.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 41, 59));
        jLabel6.setText("Account Details");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlAccountCard.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(71, 85, 105));
        jLabel7.setText("Customer ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlAccountCard.add(jLabel7, gridBagConstraints);

        customerIdField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        customerIdField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)), javax.swing.BorderFactory.createEmptyBorder(7, 9, 7, 9)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlAccountCard.add(customerIdField, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(71, 85, 105));
        jLabel8.setText("Account Type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlAccountCard.add(jLabel8, gridBagConstraints);

        accountTypeField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        accountTypeField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)), javax.swing.BorderFactory.createEmptyBorder(7, 9, 7, 9)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlAccountCard.add(accountTypeField, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(71, 85, 105));
        jLabel9.setText("Initial Balance:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlAccountCard.add(jLabel9, gridBagConstraints);

        initialBalanceField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        initialBalanceField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)), javax.swing.BorderFactory.createEmptyBorder(7, 9, 7, 9)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlAccountCard.add(initialBalanceField, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        addAccountButton.setBackground(new java.awt.Color(51, 102, 204));
        addAccountButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        addAccountButton.setText("Add Account");
        addAccountButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        addAccountButton.setBorderPainted(false);
        addAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAccountButton.setFocusPainted(false);
        addAccountButton.setOpaque(true);
        addAccountButton.addActionListener(this::addAccountButtonActionPerformed);
        jPanel1.add(addAccountButton);

        addAccountButton1.setBackground(new java.awt.Color(14, 116, 144));
        addAccountButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addAccountButton1.setForeground(new java.awt.Color(255, 255, 255));
        addAccountButton1.setText("View Customer Accounts");
        addAccountButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        addAccountButton1.setBorderPainted(false);
        addAccountButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAccountButton1.setFocusPainted(false);
        addAccountButton1.setOpaque(true);
        addAccountButton1.addActionListener(this::addAccountButton1ActionPerformed);
        jPanel1.add(addAccountButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        pnlAccountCard.add(jPanel1, gridBagConstraints);

        body.add(pnlAccountCard);

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        outputPanel.setBackground(new java.awt.Color(248, 250, 252));
        outputPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 22, 20, 22));
        outputPanel.setLayout(new java.awt.BorderLayout());

        label.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        label.setForeground(new java.awt.Color(71, 85, 105));
        label.setText("Dashboard Output");
        label.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 8, 0));
        outputPanel.add(label, java.awt.BorderLayout.NORTH);

        scrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240)));

        outputArea.setEditable(false);
        outputArea.setBackground(new java.awt.Color(255, 255, 255));
        outputArea.setColumns(50);
        outputArea.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        outputArea.setForeground(new java.awt.Color(30, 41, 59));
        outputArea.setRows(8);
        outputArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        scrollPane.setViewportView(outputArea);

        outputPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(outputPanel, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(920, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersButtonActionPerformed
    new CustomerListFrame().setVisible(true);    
    }//GEN-LAST:event_customersButtonActionPerformed

    private void accountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsButtonActionPerformed
    new AccountListFrame().setVisible(true);    
    }//GEN-LAST:event_accountsButtonActionPerformed

    private void transactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionButtonActionPerformed
    new TransactionFrame().setVisible(true);
    }//GEN-LAST:event_transactionButtonActionPerformed

    private void logsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsButtonActionPerformed
    new TransactionLogsFrame().setVisible(true);
    }//GEN-LAST:event_logsButtonActionPerformed

    private void addAccountButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountButton1ActionPerformed
    try {
            int customerId = readInt(customerIdField, "Customer ID");
            Customer customer = customerDAO.getCustomerById(customerId);

            if (customer == null) {
                showError("Customer not found.");
                return;
            }

            List<Account> accounts = accountDAO.getAccountsByCustomerId(customerId);
            StringBuilder builder = new StringBuilder();
            builder.append(customer).append("\n\n");

            if (accounts.isEmpty()) {
                builder.append("No accounts found for this customer.");
            } else {
                for (Account account : accounts) {
                    builder.append(account).append("\n");
                }
            }

            outputArea.setText(builder.toString());
        } catch (IllegalArgumentException | SQLException ex) {
            showError(ex.getMessage());
        }    
    }//GEN-LAST:event_addAccountButton1ActionPerformed

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
    try {
            Customer customer = new Customer(
                    0,
                    requiredText(firstNameField, "First name"),
                    requiredText(lastNameField, "Last name"),
                    requiredText(emailField, "Email"),
                    requiredText(phoneField, "Phone number"));

            int customerId = customerDAO.addCustomer(customer);
            outputArea.setText("Customer added successfully.\nCustomer ID: " + customerId);
            clearCustomerFields();
        } catch (IllegalArgumentException | SQLException ex) {
            showError(ex.getMessage());
        }   
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void addAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountButtonActionPerformed
    try {
            int customerId = readInt(customerIdField, "Customer ID");

            if (customerDAO.getCustomerById(customerId) == null) {
                showError("Customer not found.");
                return;
            }

            BigDecimal initialBalance = readAmount(initialBalanceField, "Initial balance");
            Account account = new Account(
                    0,
                    requiredText(accountTypeField, "Account type"),
                    initialBalance,
                    customerId);

            int accountId = accountDAO.addAccount(account);

            if (initialBalance.compareTo(BigDecimal.ZERO) > 0) {
                transactionDAO.addTransaction(new Transaction(0, accountId, "Initial Deposit", initialBalance, null));
            }

            outputArea.setText("Account added successfully.\nAccount ID: " + accountId);
            clearAccountFields();
        } catch (IllegalArgumentException | SQLException ex) {
            showError(ex.getMessage());
        }      
    }//GEN-LAST:event_addAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountTypeField;
    private javax.swing.JButton accountsButton;
    private javax.swing.JButton addAccountButton;
    private javax.swing.JButton addAccountButton1;
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JPanel body;
    private javax.swing.JLabel customerDetailsTitle;
    private javax.swing.JTextField customerIdField;
    private javax.swing.JButton customersButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField initialBalanceField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton logsButton;
    private javax.swing.JPanel navPanel;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JPanel pnlAccountCard;
    private javax.swing.JPanel pnlCustomerCard;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel textPanel;
    private javax.swing.JButton transactionButton;
    // End of variables declaration//GEN-END:variables
}
