/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingsystem_nerosa;

import java.math.BigDecimal;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author FernanCarl
 */
public class TransactionFrame extends javax.swing.JFrame {
    
    private final AccountDAO accountDAO = new AccountDAO();
    private final TransactionDAO transactionDAO = new TransactionDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionFrame.class.getName());

    /**
     * Creates new form TransactionFrame
     */
    public TransactionFrame() {
        initComponents();
    }
    
    private void submitTransaction() {
        try {
            int accountId = readAccountId();
            BigDecimal amount = readAmount();
            Account account = accountDAO.getAccountById(accountId);

            if (account == null) {
                showError("Account not found.");
                return;
            }

            boolean success;
            String type;

            if (depositButton.isSelected()) {
                success = accountDAO.deposit(accountId, amount);
                type = "Deposit";
            } else {
                success = accountDAO.withdraw(accountId, amount);
                type = "Withdraw";
            }

            if (!success) {
                showError("Transaction failed. Please check the account balance.");
                return;
            }

            transactionDAO.addTransaction(new Transaction(0, accountId, type, amount, null));
            JOptionPane.showMessageDialog(this, type + " successful.");
            amountField.setText("");
            checkBalance();
        } catch (IllegalArgumentException | SQLException ex) {
            showError(ex.getMessage());
        }
    }
    
    private void checkBalance() {
        try {
            int accountId = readAccountId();
            Account account = accountDAO.getAccountById(accountId);

            if (account == null) {
                showError("Account not found.");
                return;
            }

            balanceLabel.setText("Balance: " + account.getBal());
        } catch (IllegalArgumentException | SQLException ex) {
            showError(ex.getMessage());
        }
    }
    
    private int readAccountId() {
        try {
            return Integer.parseInt(accountIdField.getText().trim());
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Account ID must be a valid number.");
        }
    }

    private BigDecimal readAmount() {
        try {
            BigDecimal amount = new BigDecimal(amountField.getText().trim());

            if (amount.compareTo(BigDecimal.ZERO) <= 0) {
                throw new IllegalArgumentException("Amount must be greater than zero.");
            }

            return amount;
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Amount must be a valid number.");
        }
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupTransaction = new javax.swing.ButtonGroup();
        headerPanel = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        wrapper = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        accountIdLabel = new javax.swing.JLabel();
        accountIdField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typePanel = new javax.swing.JPanel();
        depositButton = new javax.swing.JRadioButton();
        withdrawButton = new javax.swing.JRadioButton();
        balanceLabel = new javax.swing.JLabel();
        actionPanel = new javax.swing.JPanel();
        checkBalanceButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banking System - Transaction");
        setBackground(new java.awt.Color(248, 250, 252));

        headerPanel.setBackground(new java.awt.Color(22, 78, 99));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 22, 18, 22));
        headerPanel.setLayout(new java.awt.BorderLayout());

        textPanel.setOpaque(false);
        textPanel.setLayout(new java.awt.BorderLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Transaction");
        textPanel.add(title, java.awt.BorderLayout.NORTH);

        subtitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        subtitle.setForeground(new java.awt.Color(207, 250, 254));
        subtitle.setText("Deposit or withdraw funds from an account.");
        subtitle.setToolTipText("");
        textPanel.add(subtitle, java.awt.BorderLayout.SOUTH);

        headerPanel.add(textPanel, java.awt.BorderLayout.WEST);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        wrapper.setBackground(new java.awt.Color(248, 250, 252));
        wrapper.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 22, 12, 22));
        wrapper.setLayout(new java.awt.BorderLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240)), javax.swing.BorderFactory.createEmptyBorder(18, 18, 18, 18)));
        panel.setLayout(new java.awt.GridBagLayout());

        accountIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        accountIdLabel.setText("Account ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        panel.add(accountIdLabel, gridBagConstraints);

        accountIdField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        accountIdField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)), javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        panel.add(accountIdField, gridBagConstraints);

        amountLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        amountLabel.setText("Amount:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        panel.add(amountLabel, gridBagConstraints);

        amountField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        amountField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)), javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        panel.add(amountField, gridBagConstraints);

        typeLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        typeLabel.setText("Transaction Type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        panel.add(typeLabel, gridBagConstraints);

        typePanel.setBackground(new java.awt.Color(255, 255, 255));

        depositButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTransaction.add(depositButton);
        depositButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        depositButton.setForeground(new java.awt.Color(30, 41, 59));
        depositButton.setSelected(true);
        depositButton.setText("Deposit");
        depositButton.setFocusPainted(false);
        typePanel.add(depositButton);

        withdrawButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTransaction.add(withdrawButton);
        withdrawButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        withdrawButton.setForeground(new java.awt.Color(30, 41, 59));
        withdrawButton.setText("Withdraw");
        withdrawButton.setFocusPainted(false);
        typePanel.add(withdrawButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        panel.add(typePanel, gridBagConstraints);

        balanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(22, 78, 99));
        balanceLabel.setText("Balance:");
        balanceLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 251, 241)), javax.swing.BorderFactory.createEmptyBorder(12, 14, 12, 14)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel.add(balanceLabel, gridBagConstraints);

        wrapper.add(panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(wrapper, java.awt.BorderLayout.CENTER);

        actionPanel.setBackground(new java.awt.Color(248, 250, 252));
        actionPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 22, 22, 22));

        checkBalanceButton.setBackground(new java.awt.Color(51, 102, 204));
        checkBalanceButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkBalanceButton.setForeground(new java.awt.Color(255, 255, 255));
        checkBalanceButton.setText("Check Balance");
        checkBalanceButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        checkBalanceButton.setBorderPainted(false);
        checkBalanceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkBalanceButton.setFocusPainted(false);
        checkBalanceButton.addActionListener(this::checkBalanceButtonActionPerformed);
        actionPanel.add(checkBalanceButton);

        submitButton.setBackground(new java.awt.Color(14, 116, 144));
        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        submitButton.setBorderPainted(false);
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.setFocusPainted(false);
        submitButton.addActionListener(this::submitButtonActionPerformed);
        actionPanel.add(submitButton);

        closeButton.setBackground(new java.awt.Color(226, 232, 240));
        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closeButton.setForeground(new java.awt.Color(30, 41, 59));
        closeButton.setText("Close");
        closeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        closeButton.setBorderPainted(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.setFocusPainted(false);
        closeButton.addActionListener(this::closeButtonActionPerformed);
        actionPanel.add(closeButton);

        getContentPane().add(actionPanel, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(560, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBalanceButtonActionPerformed
    checkBalance();        
    }//GEN-LAST:event_checkBalanceButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
    submitTransaction();    
    }//GEN-LAST:event_submitButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountIdField;
    private javax.swing.JLabel accountIdLabel;
    private javax.swing.JPanel actionPanel;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.ButtonGroup buttonGroupTransaction;
    private javax.swing.JButton checkBalanceButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JRadioButton depositButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel panel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel subtitle;
    private javax.swing.JPanel textPanel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JPanel typePanel;
    private javax.swing.JRadioButton withdrawButton;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables
}
