/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingsystem_nerosa;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author FernanCarl
 */
public class TransactionLogsFrame extends javax.swing.JFrame {
    
    private final AccountDAO accountDAO = new AccountDAO();
    private final TransactionDAO transactionDAO = new TransactionDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionLogsFrame.class.getName());

    /**
     * Creates new form TransactionLogsFrame
     */
    public TransactionLogsFrame() {
        initComponents();
        
        JTableHeader header = tblLogs.getTableHeader();
        header.setBackground(new Color(241, 245, 249));
        header.setForeground(new Color(30, 41, 59));
        header.setFont(new Font("Segoe UI", Font.BOLD, 13));
        header.setReorderingAllowed(false);
    }
    
    private static class StripeRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected,
                boolean focused, int row, int column) {
            Component component = super.getTableCellRendererComponent(table, value, selected, focused, row, column);
            setBorder(BorderFactory.createEmptyBorder(0, 12, 0, 12));

            if (!selected) {
                component.setBackground(row % 2 == 0 ? Color.WHITE : new Color(248, 250, 252));
                component.setForeground(new Color(30, 41, 59));
            }

            return component;
        }
    }
    
    private void loadLogs() {
        DefaultTableModel tableModel = (DefaultTableModel) tblLogs.getModel();
        try {
            int accountId = readAccountId();

            if (accountDAO.getAccountById(accountId) == null) {
                showError("Account not found.");
                return;
            }

            List<Transaction> transactions = transactionDAO.getTransactionsByAccountId(accountId);
            tableModel.setRowCount(0);

            for (Transaction transaction : transactions) {
                tableModel.addRow(new Object[]{
                    transaction.getTransaction_id(),
                    transaction.getTransaction_type(),
                    transaction.getAmount(),
                    transaction.getTransaction_date(),
                    transaction.getAccount_id()
                });
            }

            countLabel.setText(transactions.size() + " transactions");

            if (transactions.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No transactions found for this account.");
            }
        } catch (IllegalArgumentException | SQLException ex) {
            showError(ex.getMessage());
        }
    }

    private void clearLogs() {
        DefaultTableModel tableModel = (DefaultTableModel) tblLogs.getModel();
        accountIdField.setText("");
        tableModel.setRowCount(0);
        countLabel.setText("0 transactions");
    }
    
    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private int readAccountId() {
        try {
            return Integer.parseInt(accountIdField.getText().trim());
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Account ID must be a valid number.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        accountIdField = new javax.swing.JTextField(12);
        searchButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogs = new javax.swing.JTable();
        footer = new javax.swing.JPanel();
        countLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banking System - Transaction Logs");
        setBackground(new java.awt.Color(248, 250, 252));

        headerPanel.setBackground(new java.awt.Color(22, 78, 99));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 22, 18, 22));
        headerPanel.setLayout(new java.awt.BorderLayout());

        textPanel.setOpaque(false);
        textPanel.setLayout(new java.awt.BorderLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Accounts");
        textPanel.add(title, java.awt.BorderLayout.NORTH);

        subtitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        subtitle.setForeground(new java.awt.Color(207, 250, 254));
        subtitle.setText("Right-click a row to update or delete an account.");
        subtitle.setToolTipText("");
        textPanel.add(subtitle, java.awt.BorderLayout.SOUTH);

        headerPanel.add(textPanel, java.awt.BorderLayout.WEST);

        searchPanel.setOpaque(false);
        searchPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Account ID:");
        searchPanel.add(jLabel1);

        accountIdField.setBackground(new java.awt.Color(255, 255, 255));
        accountIdField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        accountIdField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)), javax.swing.BorderFactory.createEmptyBorder(7, 9, 7, 9)));
        searchPanel.add(accountIdField);

        searchButton.setBackground(new java.awt.Color(51, 102, 204));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        searchButton.setBorderPainted(false);
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.setFocusPainted(false);
        searchButton.addActionListener(this::searchButtonActionPerformed);
        searchPanel.add(searchButton);

        clearButton.setBackground(new java.awt.Color(14, 116, 144));
        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        clearButton.setBorderPainted(false);
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.setFocusPainted(false);
        clearButton.addActionListener(this::clearButtonActionPerformed);
        searchPanel.add(clearButton);

        jButton3.setBackground(new java.awt.Color(226, 232, 240));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(30, 41, 59));
        jButton3.setText("Close");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(9, 16, 9, 16));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        searchPanel.add(jButton3);

        headerPanel.add(searchPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 8, 16));

        tblLogs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Amount", "Date", "Account ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLogs.setRowHeight(34);
        tblLogs.setSelectionBackground(new java.awt.Color(214, 229, 255));
        tblLogs.setSelectionForeground(new java.awt.Color(20, 28, 43));
        tblLogs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblLogs.setShowGrid(false);
        tblLogs.setDefaultRenderer(Object.class, new StripeRenderer());
        tblLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLogsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblLogs);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(248, 250, 252));
        footer.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 22, 18, 22));
        footer.setLayout(new java.awt.BorderLayout());

        countLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        countLabel.setForeground(new java.awt.Color(71, 85, 105));
        countLabel.setText("0 accounts");
        footer.add(countLabel, java.awt.BorderLayout.WEST);

        getContentPane().add(footer, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(760, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblLogsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLogsMousePressed
        int row = tblLogs.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            tblLogs.setRowSelectionInterval(row, row);
        }
    }//GEN-LAST:event_tblLogsMousePressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
    loadLogs();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
    clearLogs();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    dispose();        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionLogsFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountIdField;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel countLabel;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel subtitle;
    private javax.swing.JTable tblLogs;
    private javax.swing.JPanel textPanel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
